### ISSUE TITLE
jQuery. Подробное руководство по продвинутому JavaScript

### ISSUE THREAD

**Issue by skinet2009** [andrew--r/frontendbookshelf#10]
jQuery in Action
Авторы: Беэр Бибо, Иегуда Кац
Издательство: Символ-Плюс
Серия: High Tech
ISBN 978-5-93286-201-8, 978-1-935182-32-0; 2011 г.

Дополнительные характеристики
Переводчик Александр Киселев
Язык Русский
Страниц 624 стр.
Формат 70x100/16 (170x240 мм)
Тираж 1200 экз.
Переплет Мягкая обложка

Доступные издания:
Мягкая обложка  2009 г.
Мягкая обложка  2011 г.

Ссылка для скачки: https://vk.com/wall-54530371_3455

**Comment by MacOSO** [comment]
Links for purchase: https://www.manning.com/books/jquery-in-action , http://www.books.ru/books/jquery-podrobnoe-rukovodstvo-po-prodvinutomu-javascript-619339/

**Comment by andrew--r** [comment]
266c0bfc90e21f954b18060dcf59b2fcb7ab9d7f
