### ISSUE TITLE
Пару книг и совет

### ISSUE THREAD

**Issue by ZvezdocheTag** [andrew--r/frontendbookshelf#20]
1. Less. Путеводитель для новичков
   https://www.gitbook.com/book/mrmlnc/less-guidebook-for-beginners/details
2. Э. Вейл
   HTML5. Разработка приложений для мобильных устройств
3. Никсон Р.
   Создаем динамические веб-сайты с помощью
   PHP, MySQL, JavaScript и CSS
   2-е издание

Еще такой совет сделай на главной выборку книг из различной категории , и добавь в сортировку категорию все книги, иногда человек не знает чего хочет и нужно поклацать все что есть.

**Comment by mrmlnc** [comment]
@ZvezdocheTag ну тут явно лайк за себя любимого :books: :cake: :coffee:

**Comment by ZvezdocheTag** [comment]
@mrmlnc достойная инфа по Less, помогла в нем освоиться. Так, что спасибо тебе  :v:  :+1:
