### ISSUE TITLE
 Add books on Javascript

### ISSUE THREAD

**Issue by batyshkaLenin** [andrew--r/frontendbookshelf#5]
# **JavaScript**

Автор: Cody Lindley 
Название книги: Javascript Enlightenment
Сайт книги: http://www.javascriptenlightenment.com/ 
Скачать книгу: http://www.javascriptenlightenment.com/JavaScript_Enlightenment.pdf
Уровень знаний: средний 

---

Автор книги: Marijn Haverbeke
Название книги: Eloquent Javascript
Сайт книги: http://eloquentjavascript.net/
Скачать книгу: http://eloquentjavascript.net/1st_edition/contents.html
Уровень знаний: начинающий

---

Автор книги: Alex Young
Название книги: Building A JavaScript Framework
Сайт книги: http://dailyjs.com/
Скачать книгу: https://s3.amazonaws.com/dailyjs/files/build-a-javascript-framework.pdf
Уровень знаний: продвинутый

---

Автор книги: TJ Holowaychuk
Название книги: Mastering NodeJS
Сайт книги: http://visionmedia.github.io/masteringnode/
Скачать книгу: github.com/visionmedia/masteringnode/raw/master/book.pdf
Уровень знаний: продвинутый

---

Автор книги: E. Hoigaard
Название книги: Smooth CoffeeScript
Сайт книги: http://autotelicum.github.io/Smooth-CoffeeScript/
Скачать книгу: http://autotelicum.github.io/Smooth-CoffeeScript/interactive/interactive-coffeescript.html
Уровень знаний: средний

---

Автор книги: Manuel Kiessling
Название книги: Node Beginner
Сайт книги: http://www.nodebeginner.ru/
Скачать книгу: http://www.nodebeginner.ru/#about
Уровень знаний: средний

---

Автор книги: Rebecca Murphey
Название книги: jQuery Fundamentals
Сайт книги: http://jqfundamentals.com/
Скачать книгу: http://jqfundamentals.com/
Уровень знаний: начальный

**Comment by andrew--r** [comment]
7569422f20a18004358cbaa176a84a14ed069762, c1942147a1502a2da8eaf5bbc384fd54c3f15fef
